name: demandium_serviceman
description: A new Flutter project.

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  intl: ^0.20.2
  http: ^1.3.0
  flutter_avif: ^3.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  country_code_picker: 3.1.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.16.0
  shimmer_animation: ^2.2.2
  fl_chart: ^0.70.2
  dotted_border: ^2.1.0
  flutter_local_notifications: ^18.0.1
  file_picker: ^9.0.2
  pdf: ^3.11.1
  open_file: ^3.5.10
  flutter_downloader: ^1.12.0
  dio: ^5.8.0+1
  permission_handler: ^11.4.0
  printing: ^5.14.2
  flutter_switch: ^0.3.2
  photo_view: ^0.15.0
  scroll_to_index: any
  phone_numbers_parser: ^9.0.3
  firebase_auth: ^5.5.1
  table_calendar: ^3.2.0

  #open_file_plus: ^3.4.1+1
  provider: ^6.1.5
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
  flutter_image_compress: ^2.4.0
  #  open_file_plus: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
    


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

flutter_launcher_icons:
  android: true
  ios: true

  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/logo.png"
    #adaptive_icon_foreground: "assets/images/logo.png"

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
