// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTURUJzMAYiyDO60jCBz5zb70jytshH2c',
    appId: '1:199624523333:web:1a255a2a7d7219901fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    authDomain: 'madad-4b373.firebaseapp.com',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    measurementId: 'G-XCFX3D8HCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3J9I6f7YSC0x8TvtNcl48O87mb8CZ0Y',
    appId: '1:199624523333:android:340b31aed69a90011fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKIWqTr7RpFozF6Gqmyx37O1HRxRXwyU',
    appId: '1:199624523333:ios:429578d3bd0f1fba1fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    iosClientId: '199624523333-0stv5ehusk1ieqdtofi8602geqj52lp0.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.demandium.serviceman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGKIWqTr7RpFozF6Gqmyx37O1HRxRXwyU',
    appId: '1:199624523333:ios:985bd13a857d33e91fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    iosClientId: '199624523333-81tm9j8akprhrih37lsos2g0o9rqq70k.apps.googleusercontent.com',
    iosBundleId: 'com.maven.madad.serviceman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTURUJzMAYiyDO60jCBz5zb70jytshH2c',
    appId: '1:199624523333:web:7eef21c7293396391fad2c',
    messagingSenderId: '199624523333',
    projectId: 'madad-4b373',
    authDomain: 'madad-4b373.firebaseapp.com',
    databaseURL: 'https://madad-4b373-default-rtdb.firebaseio.com',
    storageBucket: 'madad-4b373.firebasestorage.app',
    measurementId: 'G-BPVGKL0HFQ',
  );
}
